# Generated by Django 4.0.8 on 2023-02-22 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital_livestock', '0002_rename_animal_type_platoon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digital_livestock.village'),
        ),
    ]
