# Generated by Django 4.1.3 on 2022-12-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_livestock', '0002_rename_village_village_city_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='governorate_id',
            new_name='governorate',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='city_id',
            new_name='city',
        ),
    ]
