# Generated by Django 4.0.8 on 2023-06-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_livestock', '0002_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(upload_to='farmer_user'),
        ),
    ]
