# Generated by Django 4.0.8 on 2023-02-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_livestock', '0003_alter_user_village'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='animal_type',
            new_name='platoon',
        ),
    ]
