# Generated by Django 4.1.3 on 2022-12-02 15:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('digital_livestock', '0003_rename_governorate_id_city_governorate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='for_what_use_animal',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='connect_sub_animal_for_what',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_livestock.animal_sub_type')),
                ('for_what_use_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_livestock.for_what_use_animal')),
            ],
        ),
    ]
