# Generated by Django 4.0.8 on 2023-03-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_livestock', '0004_rename_animal_type_species_platoon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
