# Generated by Django 4.1.3 on 2022-12-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_livestock', '0005_remove_animal_sub_type_what_produce'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_sub_type',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
