# Generated by Django 4.0.8 on 2023-03-01 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_livestock', '0005_rename_name_user_fname_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(regex='[a-zA-Z]')]),
        ),
    ]
