# Generated by Django 4.1.3 on 2022-12-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_livestock', '0006_animal_sub_type_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal_sub_type',
            old_name='city',
            new_name='country',
        ),
    ]
