# Generated by Django 4.2 on 2023-12-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_livestock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customegroup',
            name='p',
        ),
    ]
