# Generated by Django 4.2 on 2023-09-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_livestock', '0002_custompermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='digital_livestock.custompermissions', verbose_name='user permissions'),
        ),
    ]
