# Generated by Django 4.2 on 2023-09-03 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_livestock', '0004_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
