# Generated by Django 4.2 on 2023-09-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_livestock', '0005_remove_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customegroup',
            name='ar_name',
            field=models.CharField(blank=True, default='kkkk', max_length=345, null=True),
        ),
    ]
